OPENAI_API_KEY = "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"

OPENAI_MODEL_3 = "gpt-3.5-turbo"

OPENAI_MODEL_4 = "gpt-4"

NEO4J_URI = "bolt://18.207.205.88:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "inclinations-odors-laser"





AZURE_SEARCH_SERVICE_ENDPOINT=https://evme-cognitivesearch.search.windows.net
AZURE_SEARCH_INDEX_NAME=search-vector-demo
AZURE_SEARCH_ADMIN_KEY=ybS3oEKYeOPj9MeEcil1JhT5SK6zidGM1pOnHg9sBMAzSeAx4aHT

AZURE_OPENAI_API_KEY=8d3a7f5791c94752be0d314e851efb7b
AZURE_OPENAI_ENDPOINT=https://stelligence.openai.azure.com/
AZURE_OPENAI_EMBEDDING_DEPLOYED_MODEL=text-embedding-ada-002

# NEO4J_URI=neo4j://104.43.13.59:7687
NEO4J_URI=neo4j://4.194.131.167/:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=P@ssword
NEO4J_DATABASE=neo4j

OPENAI_API_KEY=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
